#!/bin/bash

usage() { echo "Manual: $0 [-c <string> -f <path>]" 1>&2; exit 1; }

while getopts ":c:f:" o; do
    case "${o}" in
        c)
            c=${OPTARG}
            ;;
        f)
            f=${OPTARG}
            ;;
        *)
            usage
            ;;
    esac
done
shift $((OPTIND-1))

if [ -z "${c}" ]; then
    usage
fi

if [ -z "${f}" ]; 
then
    echo "Добавляем все что есть"
    git add .
else
    echo "Добавляем ${f}"
    git add ${f}
fi


git commit -m "${c}"
git pull origin master
git push origin master

echo "**********************************************"
echo "**********************************************"
echo "Отправил в гит"
echo "**********************************************"
echo "**********************************************"