services:
    mshop_products.repository.category:
        class: Backend\Modules\EnerIblocks\Domain\Categorys\CategoryRepository
        public: true
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - Backend\Modules\EnerIblocks\Domain\Categorys\Category
    mshop_products.repository.categorys_type:
        class: Backend\Modules\EnerIblocks\Domain\CategorysType\CategoryTypeRepository
        public: true
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - Backend\Modules\EnerIblocks\Domain\CategorysType\CategoryType
    mshop_products.repository.categorys_meta:
        class: Backend\Modules\EnerIblocks\Domain\CategorysMeta\CategoryMetaRepository
        public: true
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - Backend\Modules\EnerIblocks\Domain\CategorysMeta\CategoryMeta