services:
    mshop_products.repository.category:
        class: Backend\Modules\EnerIblocks\Domain\Categorys\CategoryRepository
        public: true
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - Backend\Modules\EnerIblocks\Domain\Categorys\Category