doctrine:
  dbal:
  orm:
    mappings:
      pay_method:
         type: annotation
         is_bundle: false
         dir: "%kernel.project_dir%/src/Backend/Modules/EnerShop/Domain/PayMethods"
         alias: Banner
         prefix: Backend\Modules\EnerShop\Domain\PayMethods
      delivery_method:
         type: annotation
         is_bundle: false
         dir: "%kernel.project_dir%/src/Backend/Modules/EnerShop/Domain/DeliveryMethods"
         alias: Banner
         prefix: Backend\Modules\EnerShop\Domain\DeliveryMethods
      status_order:
         type: annotation
         is_bundle: false
         dir: "%kernel.project_dir%/src/Backend/Modules/EnerShop/Domain/StatusOrders"
         alias: Banner
         prefix: Backend\Modules\EnerShop\Domain\StatusOrders
      order:
         type: annotation
         is_bundle: false
         dir: "%kernel.project_dir%/src/Backend/Modules/EnerShop/Domain/Orders"
         alias: Banner
         prefix: Backend\Modules\EnerShop\Domain\Orders