services:
    mshop_products.repository.pay_method:
        class: Backend\Modules\EnerShop\Domain\PayMethods\PayMethodRepository
        public: true
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - Backend\Modules\EnerShop\Domain\PayMethods\PayMethod