services:
    mshop_products.repository.pay_method:
        class: Backend\Modules\EnerShop\Domain\PayMethods\PayMethodRepository
        public: true
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - Backend\Modules\EnerShop\Domain\PayMethods\PayMethod
    mshop_products.repository.delivery_method:
        class: Backend\Modules\EnerShop\Domain\DeliveryMethods\DeliveryMethodRepository
        public: true
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - Backend\Modules\EnerShop\Domain\DeliveryMethods\DeliveryMethod
    mshop_products.repository.status_order:
        class: Backend\Modules\EnerShop\Domain\StatusOrders\StatusOrderRepository
        public: true
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - Backend\Modules\EnerShop\Domain\StatusOrders\StatusOrder